{% set build = 0 %}
{% set name = "libheif" %}
{% set version = "1.19.7" %}
# ensure license_family is defined to appease bot
{% set license_family = license_family or 'notset' %}

{%- if license_family == 'gpl' %}
{% set build = build + 100 %}
{%- endif %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/strukturag/libheif/releases/download/v{{ version }}/libheif-{{ version }}.tar.gz
  sha256: 161c042d2102665fcee3ded851c78a0eb5f2d4bfe39fba48ba6e588fd6e964f3

build:
  number: {{ build }}
  string: {{ license_family }}_h{{ PKG_HASH }}_{{ PKG_BUILDNUM }}
  run_exports:
    - {{ pin_subpackage('libheif', max_pin='x.x') }}

requirements:
  build:
    - gnuconfig  # [unix]
    - {{ compiler('cxx') }}
    - {{ stdlib('c') }}
    - cmake
    - ninja
  host:
    - libde265
    - libavif
    # - svt-av1
    # - rav1e
    - dav1d
    - aom
    - x265  # [license_family == 'gpl']

test:
  commands:
    - test -f $PREFIX/lib/libheif${SHLIB_EXT}      # [unix]
    - test -f $PREFIX/include/libheif/heif.h      # [unix]
    - test -f $PREFIX/lib/pkgconfig/libheif.pc      # [unix]
    - test -f $PREFIX/lib/cmake/libheif/libheif-config.cmake      # [unix]
    - if not exist %LIBRARY_LIB%\heif.lib exit 1       # [win]
    - if not exist %LIBRARY_BIN%\heif.dll exit 1       # [win]
    - if not exist %LIBRARY_INC%\libheif\heif.h exit 1       # [win]
    - if not exist %LIBRARY_LIB%\cmake\libheif\libheif-config.cmake exit 1       # [win]

about:
  home: https://github.com/strukturag/libheif
  summary: libheif is an HEIF and AVIF file format decoder and encoder
  description: |
    libheif is an ISO/IEC 23008-12:2017 HEIF and AVIF (AV1 Image File Format)
    file format decoder and encoder. HEIF and AVIF are new image file formats
    employing HEVC (h.265) or AV1 image coding, respectively, for the best
    compression ratios currently possible. libheif makes use of libde265 for
    HEIF image decoding and x265 for encoding. For AVIF, libaom, dav1d,
    svt-av1, or rav1e are used as codecs.
  license: LGPL-3.0-or-later
  license_family: LGPL
  license_file: COPYING
  dev_url: https://github.com/strukturag/libheif

extra:
  recipe-maintainers:
    - frmdstryr
