schema_version: 1

context:
  version: "1.23.5"
  # Reset this to 0 for each upstream release; increment it for recipe rebuilds.
  build_number: 1

package:
  name: libheif
  version: ${{ version }}

source:
  url: https://github.com/strukturag/libheif/releases/download/v${{ version }}/libheif-${{ version }}.tar.gz
  sha256: fd9036064c4432f0550d15072ddf34956a248279ee9aeaff0fba3fa0f77d8f1a

build:
  # Keep the GPL variant preferred while sharing one rebuild counter.
  number: ${{ build_number + (100 if license_family == "gpl" else 0) }}
  string: ${{ license_family }}_h${{ hash }}_${{ build_number }}

requirements:
  build:
    - if: unix
      then: gnuconfig
    - ${{ compiler("cxx") }}
    - ${{ stdlib("c") }}
    - cmake
    - ninja
  host:
    - libde265
    - libavif
    # - svt-av1
    # - rav1e
    - dav1d-devel
    - aom
    - if: license_family == "gpl"
      then: x265
  run_exports:
    - ${{ pin_subpackage("libheif", upper_bound="x.x") }}

tests:
  - package_contents:
      include:
        - libheif/heif.h
      lib:
        - heif
      files:
        exists:
          - if: win
            then: Library/lib/cmake/libheif/libheif-config.cmake
            else: lib/cmake/libheif/libheif-config.cmake
          - if: unix
            then: lib/pkgconfig/libheif.pc
  - files:
      recipe:
        - test/*
    requirements:
      run:
        - ${{ compiler("cxx") }}
        - cmake
        - ninja
    script:
      - if: unix
        then:
          - cmake ${CMAKE_ARGS} -G Ninja -S test -B test_build
          - cmake --build test_build
          - ./test_build/test_libheif
      - if: win
        then:
          - cmake %CMAKE_ARGS% -G Ninja -S test -B test_build
          - cmake --build test_build
          - test_build\test_libheif.exe

about:
  homepage: https://github.com/strukturag/libheif
  summary: libheif is an HEIF and AVIF file format decoder and encoder
  description: |
    libheif is an ISO/IEC 23008-12:2017 HEIF and AVIF (AV1 Image File Format)
    file format decoder and encoder. HEIF and AVIF are new image file formats
    employing HEVC (h.265) or AV1 image coding, respectively, for the best
    compression ratios currently possible. libheif makes use of libde265 for
    HEIF image decoding and x265 for encoding. For AVIF, libaom, dav1d,
    svt-av1, or rav1e are used as codecs.
  license: LGPL-3.0-or-later
  license_file: COPYING
  repository: https://github.com/strukturag/libheif

extra:
  recipe-maintainers:
    - jeongseok-meta
    - frmdstryr
